# Generated by Django 4.0.6 on 2022-07-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_addprojects_langage3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addprojects',
            name='link_projet',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
